# Metric-based Quantum Architecture Search

## Required imports

In [29]:
import numpy as np
import scipy

import time
import os

from itertools import combinations, product
from functools import reduce
import copy

import pennylane as qml
from pennylane.templates.layers import RandomLayers
# from pennylane import numpy as np

import tensorflow as tf
from tensorflow import keras

from tensorflow.keras import layers

import matplotlib.pyplot as plt

from sklearn.datasets import make_moons

from scipy.stats import spearmanr

# import gym

In [54]:
!pip install torch torchquantum

  Using cached torch-1.13.0-cp37-cp37m-manylinux1_x86_64.whl (890.2 MB)
  Using cached torchquantum-0.1.4-py3-none-any.whl (119 kB)
  Using cached nvidia_cuda_nvrtc_cu11-11.7.99-2-py3-none-manylinux1_x86_64.whl (21.0 MB)
  Using cached nvidia_cuda_runtime_cu11-11.7.99-py3-none-manylinux1_x86_64.whl (849 kB)
  Using cached nvidia_cublas_cu11-11.10.3.66-py3-none-manylinux1_x86_64.whl (317.1 MB)
  Using cached nvidia_cudnn_cu11-8.5.0.96-2-py3-none-manylinux1_x86_64.whl (557.1 MB)
  Using cached numpy-1.21.6-cp37-cp37m-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (15.7 MB)
  Using cached torchvision-0.14.0-cp37-cp37m-manylinux1_x86_64.whl (24.3 MB)
  Using cached torchpack-0.3.1-py3-none-any.whl (34 kB)
  Using cached qiskit-0.32.1-py3-none-any.whl
  Using cached tqdm-4.64.1-py2.py3-none-any.whl (78 kB)
  Using cached pylatexenc-2.10-py3-none-any.whl
  Using cached qiskit_terra-0.18.3-cp37-cp37m-manylinux2010_x86_64.whl (6.1 MB)
  Using cached qiskit_ignis-0.6.0-py3-none-any.whl (207 kB)

In [5]:
!pip install pennylane pennylane-qiskit qiskit matplotlib

  Using cached PennyLane-0.25.1-py3-none-any.whl (1.0 MB)
  Using cached PennyLane_qiskit-0.24.0-py3-none-any.whl (34 kB)
  Using cached qiskit-0.38.0-py3-none-any.whl
  Using cached matplotlib-3.5.3-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.whl (11.2 MB)
  Using cached PennyLane_Lightning-0.25.1-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (13.6 MB)
  Using cached autoray-0.3.2-py3-none-any.whl (36 kB)
  Using cached autograd-1.4-py3-none-any.whl (48 kB)
  Using cached appdirs-1.4.4-py2.py3-none-any.whl (9.6 kB)
  Using cached semantic_version-2.10.0-py2.py3-none-any.whl (15 kB)
  Using cached retworkx-0.11.0-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (1.6 MB)
  Using cached networkx-2.6.3-py3-none-any.whl (1.9 MB)
  Using cached toml-0.10.2-py2.py3-none-any.whl (16 kB)
  Using cached ninja-1.10.2.3-py2.py3-none-manylinux_2_5_x86_64.manylinux1_x86_64.whl (108 kB)
  Using cached mthree-1.0.0-cp37-cp37m-manylinux

In [ ]:
!python supernet/train_search_bank.py --warmup_epochs 0 --steps 13725 --n_search 1 --n_qubits 4 --n_experts 1 --n_layers 3 --n_encode_layers 2 --save "12_params_mb_2" --data "./experiment_data/bank" --save_dir "./supernet/bank"

2022-08-16 11:01:14.995391: W tensorflow/core/profiler/internal/smprofiler_timeline.cc:460] Initializing the SageMaker Profiler.
2022-08-16 11:01:15.004850: W tensorflow/core/profiler/internal/smprofiler_timeline.cc:105] SageMaker Profiler is not enabled. The timeline writer thread will not be started, future recorded events will be dropped.
2022-08-16 11:01:15.778174: W tensorflow/core/profiler/internal/smprofiler_timeline.cc:460] Initializing the SageMaker Profiler.
(1098, 2, 4) (122, 2, 4)
subnet: [151987, 29594, 42167], expert_idx: 0
2022-08-16 11:01:35.778810: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  AVX512F
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-08-16 11:01:35.891637: I tensorflow/core/platform/profile_utils/cpu_utils.cc:104] CPU Frequency: 2500000000 Hz


In [ ]:
!python supernet/train_search_mnist.py --warmup_epochs 0 --steps 20000 --n_search 1 --n_qubits 4 --n_experts 1 --n_layers 2 --n_encode_layers 1 --save "8_params" --data "./supernet/mnist_2_data" --save_dir "./supernet/mnist_2"

In [ ]:
!python supernet/train_search_mnist.py --warmup_epochs 0 --steps 20000 --n_search 1 --n_qubits 4 --n_experts 1 --n_layers 3 --n_encode_layers 1 --save "12_params" --data "./supernet/mnist_2_data" --save_dir "./supernet/mnist_2"

In [ ]:
!python supernet/train_search_mnist.py --warmup_epochs 0 --steps 20000 --n_search 1 --n_qubits 4 --n_experts 1 --n_layers 4 --n_encode_layers 1 --save "16_params" --data "./supernet/mnist_2_data" --save_dir "./supernet/mnist_2"

In [ ]:
!python supernet/train_search_mnist.py --warmup_epochs 0 --steps 20000 --n_search 1 --n_qubits 4 --n_experts 1 --n_layers 5 --n_encode_layers 1 --save "20_params" --data "./supernet/mnist_2_data" --save_dir "./supernet/mnist_2"

2022-08-06 13:37:54.411217: W tensorflow/core/profiler/internal/smprofiler_timeline.cc:460] Initializing the SageMaker Profiler.
2022-08-06 13:37:54.411331: W tensorflow/core/profiler/internal/smprofiler_timeline.cc:105] SageMaker Profiler is not enabled. The timeline writer thread will not be started, future recorded events will be dropped.
2022-08-06 13:37:54.440569: W tensorflow/core/profiler/internal/smprofiler_timeline.cc:460] Initializing the SageMaker Profiler.
(1600, 4, 4) (400, 4, 4)
subnet: [180149, 203593, 301266, 20440, 200998], expert_idx: 0
2022-08-06 13:38:06.612676: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  AVX512F
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-08-06 13:38:06.643638: I tensorflow/core/platform/profile_utils/cpu_utils.cc:104] CPU Frequenc

## Train random circuits

In [ ]:
from datasets import load_dataset

x_train, y_train, x_test, y_test = load_dataset('bank', 'iqp', 1)

num_params = [4, 8, 12, 16, 20]

num_qubits = 4
num_embeds = 0

dev = qml.device('lightning.qubit', wires=num_qubits)

for curr_num_params in num_params:
    curr_dir = './random_fe/iqp_1/bank/{}_params'.format(curr_num_params)
    
    if not os.path.exists(curr_dir):
        os.mkdir(curr_dir)
        
    for i in range(25):
        curr_circ_dir = curr_dir + '/circ_{}'.format(i + 1)
        
        if not os.path.exists(curr_circ_dir):
            os.mkdir(curr_circ_dir)
        
        ent_prob = np.random.sample()
        cxz = np.random.sample()
        pauli = 0

        circ_gates, gate_params, inputs_bounds, weights_bounds = generate_true_random_gate_circ(num_qubits, num_embeds, curr_num_params, 
                                                                                                        ent_prob=ent_prob, 
                                                                                                        cxz_prob=cxz * ent_prob,
                                                                                                        pauli_prob=pauli * (
                                                                                                            1 - cxz) * ent_prob)
        
        circ_gates = ['h'] * num_qubits + ['rz'] * num_qubits + ['zz'] * (num_qubits - 1) + circ_gates
        gate_params = [[i] for i in range(num_qubits)] * 2 + [[i, i + 1] for i in range(num_qubits - 1)] + gate_params
        inputs_bounds = [0 for i in range(num_qubits)] + [j for j in range(2 * num_qubits - 1)] + [2 * num_qubits - 1 for i in range(len(inputs_bounds))]
        weights_bounds = [0 for i in range(3 * num_qubits - 1)] + weights_bounds
        
        np.savetxt(curr_circ_dir + '/gates.txt', circ_gates, fmt="%s")
        np.savetxt(curr_circ_dir + '/gate_params.txt', gate_params, fmt="%s")
        np.savetxt(curr_circ_dir + '/inputs_bounds.txt', inputs_bounds)
        np.savetxt(curr_circ_dir + '/weights_bounds.txt', weights_bounds)
        
        circ = create_gate_circ(dev, circ_gates, gate_params, inputs_bounds,
                                                        weights_bounds, [0], 'exp', 'adjoint') 

        losses_list = []
        accs_list = []
        
        for j in range(5):
            curr_train_dir = curr_circ_dir + '/run_{}'.format(j + 1)

            if os.path.exists(curr_train_dir):
                pass
            else:
                os.mkdir(curr_train_dir)
                        
            info = train_qnn(circ, x_train, y_train, x_test, y_test, [weights_bounds[-1]], 5490, 0.05, 1, mse_loss, verbosity=17300, 
                                                                                            loss_window=50, init_params=None, 
                                                                                            acc_thres=1.1, shuffle=True, print_loss=50)

            val_exps = [circ(x_test[i], info[-1][-1]) for i in range(len(x_test))]
            val_loss = np.array([mse_loss(y_test[k], val_exps[k]) for k in range(len(x_test))]).flatten()

            acc = np.mean(val_loss < 1)

            np.savetxt(curr_train_dir + '/params_{}.txt'.format(j + 1), info[-1])
            np.savetxt(curr_train_dir + '/losses_{}.txt'.format(j + 1), info[0])

            losses_list.append(val_loss)
            accs_list.append(acc)

        np.savetxt(curr_circ_dir + '/accs.txt', accs_list)
        np.savetxt(curr_circ_dir + '/val_losses.txt', losses_list)   

Step 1 | Sliding Loss Window : 1.0
Step 51 | Sliding Loss Window : 1.0
Step 101 | Sliding Loss Window : 1.0
Step 151 | Sliding Loss Window : 1.0
Step 201 | Sliding Loss Window : 1.0
Step 251 | Sliding Loss Window : 1.0
Step 301 | Sliding Loss Window : 1.0
Step 351 | Sliding Loss Window : 1.0
Step 401 | Sliding Loss Window : 1.0
Step 451 | Sliding Loss Window : 1.0
Step 501 | Sliding Loss Window : 1.0
Step 551 | Sliding Loss Window : 1.0
Step 601 | Sliding Loss Window : 1.0
Step 651 | Sliding Loss Window : 1.0
Step 701 | Sliding Loss Window : 1.0
Step 751 | Sliding Loss Window : 1.0
Step 801 | Sliding Loss Window : 1.0
Step 851 | Sliding Loss Window : 1.0
Step 901 | Sliding Loss Window : 1.0
Step 951 | Sliding Loss Window : 1.0
Step 1001 | Sliding Loss Window : 1.0
Step 1051 | Sliding Loss Window : 1.0
Step 1101 | Sliding Loss Window : 1.0
Step 1151 | Sliding Loss Window : 1.0
Step 1201 | Sliding Loss Window : 1.0
Step 1251 | Sliding Loss Window : 1.0
Step 1301 | Sliding Loss Window : 1

In [ ]:
from datasets import TorchDataset
from datasets_nt import load_dataset
from create_gate_circs_np import get_circ_params, TQCirc, generate_true_random_gate_circ
from train_circ_np import train_tq_model, TQMseLoss
from create_noise_models import noisy_dev_from_backend

import pickle as pkl
import torch
import os
import numpy as np

dataset = 'vowel_4'
curr_dir = f'./random/{dataset}/'

num_qubits = 4
num_embeds = 10

num_train_steps = 1000
num_test_data = 120
num_meas_qubits = 2

param_nums = [24, 28, 32, 36, 40]

loss = TQMseLoss(num_meas_qubits, 4)

dev = qml.device('lightning.qubit', wires=4)
device = 'cpu'

train_data = TorchDataset(dataset, 'angle', 1, reshape_labels=True)
test_data = TorchDataset(dataset, 'angle', 1, False, reshape_labels=True)

train_data_loader = torch.utils.data.DataLoader(train_data, batch_size=32, sampler=torch.utils.data.RandomSampler(train_data))
test_data_loader = torch.utils.data.DataLoader(test_data, batch_size=32, sampler=torch.utils.data.SequentialSampler(test_data))

for param_num in param_nums:
    curr_param_dir = curr_dir + f'{param_num}_params/'
    
    for i in range(25):    
        circ_dir = curr_param_dir + f'circ_{i + 1}'

        circ_gates, gate_params, inputs_bounds, weights_bounds = get_circ_params(circ_dir)
        
        losses_list = []
        accs_list = []

        for j in range(5):
            curr_train_dir = circ_dir + '/run_{}'.format(j + 1)

            if os.path.exists(curr_train_dir):
                pass
            else:
                os.mkdir(curr_train_dir)

            model = TQCirc(circ_gates, gate_params, inputs_bounds, weights_bounds, num_qubits, False).to(device)
            opt = torch.optim.SGD(model.parameters(), lr=0.05)

            curr_loss, curr_acc = train_tq_model(model, num_meas_qubits, opt, loss, train_data_loader, test_data_loader, num_test_data, num_train_steps, 100, 10)

            print(curr_loss, curr_acc)

            losses_list.append(curr_loss)
            accs_list.append(curr_acc)
            
            torch.save(model.state_dict(), curr_train_dir + '/model.pt')

        np.savetxt(circ_dir + '/val_losses.txt', losses_list)
        np.savetxt(circ_dir + '/accs.txt', accs_list)   

Step 1 | Loss: 2.411628246307373
Step 101 | Loss: 2.084258556365967
Step 201 | Loss: 1.9618326425552368
Step 301 | Loss: 1.87111496925354
Step 401 | Loss: 1.704941987991333
Step 501 | Loss: 1.7718193531036377
Step 601 | Loss: 1.7640342712402344
Step 701 | Loss: 1.8841875791549683
Step 801 | Loss: 1.9256436824798584
Step 901 | Loss: 1.6962889432907104
1.9027481022632566 0.43333333333333335
Step 1 | Loss: 2.4657082557678223
Step 101 | Loss: 1.7229855060577393
Step 201 | Loss: 1.8800650835037231
Step 301 | Loss: 1.9550466537475586
Step 401 | Loss: 1.7530748844146729
Step 501 | Loss: 1.412966251373291
Step 601 | Loss: 1.9659106731414795
Step 701 | Loss: 1.7361094951629639
Step 801 | Loss: 1.8087999820709229
Step 901 | Loss: 1.749774694442749
1.8503618744352401 0.43333333333333335
Step 1 | Loss: 2.793297052383423
Step 101 | Loss: 1.7977628707885742
Step 201 | Loss: 1.9883795976638794
Step 301 | Loss: 1.887660026550293
Step 401 | Loss: 1.7456462383270264
Step 501 | Loss: 1.6368268728256226
S

## human design circs

In [ ]:
from datasets import load_dataset
from create_human_design_circs import generate_human_design_circ

dataset = 'bank'
num_reps = 2

num_qubits = 4
dev = qml.device('lightning.qubit', wires=num_qubits)
meas_qubits = [0]

ours_dir = './human_design/iqp_basic/bank/'

x_train, y_train, x_test, y_test = load_dataset(dataset, 'angle', num_reps)
x_train = x_train.reshape((len(x_train), 2, 4))
x_test = x_test.reshape((len(x_test), 2, 4))

num_params = [4, 8, 12, 16, 20]
params_per_layer = 4

num_embed_layers = 2

dev = qml.device('lightning.qubit', wires=num_qubits)

var_layer_options = [[qml.RY], [qml.RX]] * 4
enc_layer_options = [[1, None], [1, None]]

for curr_num_params in num_params:
    curr_dir = ours_dir + '{}_params'.format(curr_num_params)
    
    if not os.path.exists(curr_dir):
        os.mkdir(curr_dir)
        
    curr_num_layers = curr_num_params // params_per_layer
    curr_weights_shape = (curr_num_layers, 1, num_qubits)
        
    for i in range(1):
        curr_circ_dir = curr_dir

        circ = generate_human_design_circ(dev, num_qubits, 'iqp', 'basic', num_embed_layers, curr_num_layers, enc_layer_options,
                                          var_layer_options[:curr_num_layers], meas_qubits, 'exp')
        
        losses_list = []
        accs_list = []
        
        for j in range(5):
            curr_train_dir = curr_circ_dir + '/run_{}'.format(j + 1)

            if os.path.exists(curr_train_dir):
                pass
            else:
                os.mkdir(curr_train_dir)
                        
            info = train_qnn(circ, x_train, y_train, x_test, y_test, curr_weights_shape, 5490, 0.05, 1, mse_loss, verbosity=17300, 
                                                                                            loss_window=50, init_params=None, 
                                                                                            acc_thres=1.1, shuffle=True, print_loss=50)

            val_exps = np.array([circ(x_test[i], info[-1][-1]) for i in range(len(x_test))])
            val_loss = np.array([mse_loss(y_test[k], val_exps[k]) for k in range(len(x_test))]).flatten()

            acc = np.mean(val_loss < 1)

            shape = np.array(info[-1]).shape
            
            np.savetxt(curr_train_dir + '/params_{}.txt'.format(j + 1), np.array(info[-1]).reshape(shape[0], np.product(shape[1:])))
            np.savetxt(curr_train_dir + '/losses_{}.txt'.format(j + 1), info[0])

            losses_list.append(val_loss)
            accs_list.append(acc)

        np.savetxt(curr_circ_dir + '/accs.txt', accs_list)
        np.savetxt(curr_circ_dir + '/val_losses.txt', losses_list) 

Step 1 | Sliding Loss Window : 1.5924987205584051
Step 51 | Sliding Loss Window : 1.0976258499929112
Step 101 | Sliding Loss Window : 0.9822008470315303
Step 151 | Sliding Loss Window : 1.1107763139459115
Step 201 | Sliding Loss Window : 0.9996962330206135
Step 251 | Sliding Loss Window : 0.9510468994666668
Step 301 | Sliding Loss Window : 1.107546968015732
Step 351 | Sliding Loss Window : 0.9236633878977056
Step 401 | Sliding Loss Window : 0.9858746611364476
Step 451 | Sliding Loss Window : 0.8851686645631821
Step 501 | Sliding Loss Window : 1.0946015277358183
Step 551 | Sliding Loss Window : 0.9870843419723009
Step 601 | Sliding Loss Window : 0.9933065345302952
Step 651 | Sliding Loss Window : 1.1927393435168143
Step 701 | Sliding Loss Window : 1.0039110909363953
Step 751 | Sliding Loss Window : 0.9332670832832851
Step 801 | Sliding Loss Window : 1.0237061524910933
Step 851 | Sliding Loss Window : 1.0237103597021475
Step 901 | Sliding Loss Window : 0.9494042689719276
Step 951 | Slidi

## corealltion circuits

In [71]:
from create_noise_models import noisy_dev_from_backend
from create_gate_circs import generate_random_gate_circ, generate_true_random_gate_circ, create_gate_circ, create_batched_gate_circ, get_circ_params
from datasets import load_dataset

x_train, y_train, x_test, y_test = load_dataset('mnist_2', 'angle', 2)

num_qubits = 4
num_embeds = 16
num_params = 12

noisy_backend_name = 'ibmq_lima'
noiseless_dev = qml.device('lightning.qubit', wires=num_qubits)
noisy_dev = noisy_dev_from_backend(noisy_backend_name, num_qubits)

for i in range(125, 250):
    curr_dir = './experiment_data/mnist_2/trained_circuits/circ_{}'.format(i + 1)
    circ_gates, gate_params, inputs_bounds, weights_bounds = get_circ_params(curr_dir) 

    circ = create_gate_circ(noisy_dev, circ_gates, gate_params, inputs_bounds,
                                                    weights_bounds, [0], 'exp')    

    losses_list = []
    accs_list = []
    
    for j in range(1):
        curr_train_dir = curr_dir + '/noisy_run_{}'.format(j + 1)

        if os.path.exists(curr_train_dir):
            pass
        else:
            os.mkdir(curr_train_dir)
    
        
        info = train_qnn(circ, x_train, y_train, x_test, y_test, [num_params], 8000, 0.05, 1, mse_loss, verbosity=17300, 
                                                                                        loss_window=50, init_params=None, 
                                                                                        acc_thres=1.1, shuffle=True, print_loss=50)
        
        val_exps = [circ(x_test[i], info[-1][-1]) for i in range(len(x_test))]
        val_loss = np.array([mse_loss(y_test[k], val_exps[k]) for k in range(len(x_test))]).flatten()

        acc = np.mean(val_loss < 1)
        
        np.savetxt(curr_train_dir + '/params_{}.txt'.format(j + 1), info[-1])
        np.savetxt(curr_train_dir + '/losses_{}.txt'.format(j + 1), info[0])
        
        losses_list.append(val_loss)
        accs_list.append(acc)
        
    np.savetxt(curr_dir + '/noisy_val_losses.txt', losses_list)
    np.savetxt(curr_dir + '/noisy_accs.txt', accs_list)

ibmqfactory.load_account:WARNING:2022-07-25 12:25:03,282: Credentials are already in use. The existing account in the session will be replaced.


Step 1 | Sliding Loss Window : 0.7622108459472656
Step 51 | Sliding Loss Window : 0.8179362487792968


KeyboardInterrupt: 

## Train circuits using our method

In [ ]:
from datasets_nt import load_dataset
from create_gate_circs import get_circ_params, create_gate_circ
from train_circ import train_qnn, mse_loss
from create_noise_models import noisy_dev_from_backend

search_nums = [100]
param_nums = [4, 8, 12, 16, 20]

dataset = 'mnist_2'
num_reps = 1

num_qubits = 4
dev = qml.device('lightning.qubit', wires=num_qubits)
meas_qubits = [0]
mat_size = 1024

device_name = 'ibmq_lima'
noisy_dev = noisy_dev_from_backend(device_name, num_qubits)

ours_dir = './ours/mnist_2/'

x_train, y_train, x_test, y_test = load_dataset(dataset, 'angle', num_reps)

for search_num in search_nums:       
    for param_num in param_nums:
        noise_scores = []
        
        for i in range(2500):
            noise_scores.append(np.genfromtxt(ours_dir + '/{}_params/circ_{}/noise_metric/{}/metric_tvd_score.txt'.format(param_num, i + 1, device_name)))
            
        noise_scores = np.array(noise_scores)
        
        mean_t_mat_scores = np.genfromtxt(ours_dir + '{}_params/d2_mean_t_mat_scores.txt'.format(param_num))
        perf_scores = (mat_size - mean_t_mat_scores) / mat_size
        combined_scores = np.multiply(perf_scores, noise_scores)
        
        circ_inds = np.random.permutation(2500)
        
        curr_dir = ours_dir + '/{}_params/search_{}_{}'.format(param_num, search_num, device_name)
        
        if not os.path.exists(curr_dir):
            os.mkdir(curr_dir)

        for j in range(25):
            curr_trial_dir = curr_dir + '/trial_{}'.format(j + 1)

            if not os.path.exists(curr_trial_dir):
                os.mkdir(curr_trial_dir)
        
            sel_inds = circ_inds[range(j * 100, j * 100 + 100)]
            sel_ind = sel_inds[np.argmax(combined_scores[sel_inds])]

            np.savetxt(curr_trial_dir + '/searched_circuit_inds.txt', sel_inds)
            np.savetxt(curr_trial_dir + '/searched_circuit_scores.txt', combined_scores[sel_inds])
            np.savetxt(curr_trial_dir + '/sel_circuit_ind.txt', [sel_ind])
            np.savetxt(curr_trial_dir + '/sel_circuit_score.txt', [combined_scores[sel_ind]])
            
            print(sel_inds, combined_scores[sel_inds])
            print(sel_ind, combined_scores[sel_ind])
            print(noise_scores[sel_ind], perf_scores[sel_ind])

            circ_gates, gate_params, inputs_bounds, weights_bounds = get_circ_params(ours_dir + '{}_params/circ_{}'.format(param_num, sel_ind + 1))

            circ = create_gate_circ(dev, circ_gates, gate_params, inputs_bounds,
                                                                weights_bounds, meas_qubits, 'exp', 'adjoint')
            
            noisy_circ = create_gate_circ(noisy_dev, circ_gates, gate_params, inputs_bounds,
                                                                weights_bounds, meas_qubits, 'exp', None)
        
            losses_list = []
            accs_list = []
            noisy_losses_list = []
            noisy_accs_list = []

            for j in range(5):
                curr_train_dir = curr_trial_dir + '/run_{}'.format(j + 1)

                if os.path.exists(curr_train_dir):
                    pass
                else:
                    os.mkdir(curr_train_dir)


                info = train_qnn(circ, x_train, y_train, x_test, y_test, [weights_bounds[-1]], 8000, 0.05, 1, mse_loss, verbosity=17300, 
                                                                                                loss_window=50, init_params=None, 
                                                                                                acc_thres=1.1, shuffle=True, print_loss=50)

                val_exps = [circ(x_test[i], info[-1][-1]) for i in range(len(x_test))]
                val_loss = np.array([mse_loss(y_test[k], val_exps[k]) for k in range(len(x_test))]).flatten()
                
                noisy_val_exps = [noisy_circ(x_test[i], info[-1][-1]) for i in range(len(x_test))]
                noisy_val_loss = np.array([mse_loss(y_test[k], noisy_val_exps[k]) for k in range(len(x_test))]).flatten()

                acc = np.mean(val_loss < 1)
                noisy_acc = np.mean(noisy_val_loss < 1)
#                 acc = np.mean(np.sum(np.multiply(val_exps, y_test) > 0, 1) == 2)

                np.savetxt(curr_train_dir + '/params_{}.txt'.format(j + 1), info[-1])
                np.savetxt(curr_train_dir + '/losses_{}.txt'.format(j + 1), info[0])             

                losses_list.append(val_loss)
                accs_list.append(acc)
                
                noisy_losses_list.append(noisy_val_loss)
                noisy_accs_list.append(noisy_acc)

            np.savetxt(curr_trial_dir + '/accs.txt', accs_list)
            np.savetxt(curr_trial_dir + '/val_losses.txt', losses_list)          
            np.savetxt(curr_trial_dir + '/noisy_accs.txt', noisy_accs_list)
            np.savetxt(curr_trial_dir + '/noisy_val_losses.txt', noisy_losses_list) 

ibmqfactory.load_account:WARNING:2022-09-26 18:02:54,638: Credentials are already in use. The existing account in the session will be replaced.


[1845  527  337 2133  613 1031  425 1693  253  778 1504  649  556  335
 1835 1850  181 2302 2319 1516  790 1624 2395 1311 1802   72 1909 2379
 2038 1273  719 1742 1373 1005 1787 1677  867  700 1874 1180 2442  757
 1626  898 1234 1708 2184 1664 1173 2429  121 1493 2048 1397 2393   25
 1324 1089 2476  502 1757 1140    0 1368 1650 1741  202 2060  462 2080
  349 1276  653 1359 1448  354  699  473  387 1800 1215  256 1152 2375
  510 1616 1156 2296 1659 2008 2092  323 1916 2286  548 1549 1725 1282
 1663 1046] [0.60325466 0.8559179  0.69504759 0.61306607 0.15563578 0.56608088
 0.63483615 0.53375734 0.7969     0.73237812 0.70316331 0.45156479
 0.69729897 0.70605465 0.5544177  0.44095612 0.63177041 0.45186768
 0.75717001 0.80549255 0.55457483 0.43516625 0.62041871 0.57610212
 0.52165473 0.83328292 0.81908834 0.60584941 0.44481659 0.64713264
 0.60952137 0.53499092 0.62897627 0.76478013 0.46448135 0.55007498
 0.62430713 0.59193735 0.48028278 0.66957548 0.59333223 0.43913296
 0.39690399 0.81398039

## supernet

In [3]:
def convert_supernet_circ_into_gate_circ(subnet, num_embeds, layer_rots, layer_cnots, num_qubits, angle_embed=False):
    circ_gates = []
    gate_params = []
    weights_bounds = [0]
    inputs_bounds = [0]

    curr_layers = subnet
    num_cnots = len(layer_cnots)
    
    for i in range(1):
        num_qubits = len(layer_rots[0])

        if angle_embed:
            rots = ['ry', 'rx', 'rz']
            
            for j in range(num_embeds):
                circ_gates += [rots[j % 3] for i in range(num_qubits)]
                gate_params += [[i] for i in range(num_qubits)]
                weights_bounds += [0 for i in range(num_qubits)]
                inputs_bounds += [inputs_bounds[-1] + i + 1 for i in range(2 * num_qubits - 1)]            
        else:
            for j in range(num_embeds):
                circ_gates += ['h' for i in range(num_qubits)] + ['ry' for i in range(num_qubits)] + ['cry' for i in range(num_qubits - 1)]
                gate_params += [[i] for i in range(num_qubits)] * 2 + [[i, i + 1] for i in range(num_qubits - 1)]
                weights_bounds += [0 for i in range(3 * num_qubits - 1)]
                inputs_bounds += [inputs_bounds[-1] for i in range(num_qubits)] + [inputs_bounds[-1] + i + 1 for i in range(2 * num_qubits - 1)]

        for j in range(len(curr_layers)):
            circ_gates += layer_rots[curr_layers[j] // num_cnots]
            circ_gates += ['cx' for k in layer_cnots[curr_layers[j] % num_cnots]]

            gate_params += [[k] for k in range(len(layer_rots[curr_layers[j] // num_cnots]))]
            gate_params += layer_cnots[curr_layers[j] % num_cnots]

            weights_bounds += [weights_bounds[-1] + k + 1 for k in range(num_qubits)]
            inputs_bounds += [inputs_bounds[-1] for k in range(num_qubits)]

            weights_bounds += [weights_bounds[-1] for k in range(len(layer_cnots[curr_layers[j] % num_cnots]))]
            inputs_bounds += [inputs_bounds[-1] for k in range(len(layer_cnots[curr_layers[j] % num_cnots]))]
            
    return circ_gates, gate_params, inputs_bounds, weights_bounds

In [ ]:
import pennylane as qml
import numpy as np
import os

from datasets_nt import load_dataset
from create_gate_circs import create_gate_circ
from create_noise_models import noisy_dev_from_backend

dataset = 'fmnist_4'
main_dir = './supernet/fmnist_4/'

x_train, y_train, x_test, y_test = load_dataset(dataset, 'supernet', 1)

inds = np.random.choice(len(x_test), 400, False)
x_test = x_test[inds]
y_test = y_test[inds]

num_qubits = 4
num_cnot_configs = 4096
num_circs = 2500
num_embed_layers = 2

device_name = 'ibm_nairobi'
# dev = qml.device('lightning.qubit', wires=num_qubits)
dev = noisy_dev_from_backend(device_name, num_qubits)

param_nums = [12, 16]

for p in param_nums:
    supernet_dir = main_dir + 'search-{}_params_mb'.format(p)

    num_layers = p // num_qubits

    layer_rots = open(supernet_dir + '/rotations.txt').read().split('\n')[:-1]
    layer_rots = [''.join([j for j in i if j.isupper()]) for i in layer_rots]
    layer_rots = [[i[j * 2:j * 2 + 2].lower() for j in range(len(i) // 2)] for i in layer_rots]

    layer_cnots = open(supernet_dir + '/cnots.txt').read().split('\n')[:-1]
    layer_cnots = [''.join([j for j in i[1:] if j not in ['[', ']', ',', ' ']]) for i in layer_cnots]
    layer_cnots = [[[int(i[2 * j]), int(i[2 * j + 1])] for j in range(len(i) // 2)] for i in layer_cnots]
        
    search_space = len(layer_rots) * len(layer_cnots)
        
    accs = []
    losses = []
    circ_layers = []

    params = np.array([float(j) for j in open(supernet_dir + '/training_params.txt').read().split('\n')[-2].split(' ')]).reshape(num_layers, len(layer_rots), num_qubits)
#     params = np.genfromtxt(supernet_dir + '/training_params.txt')[-1].reshape((num_layers, search_space // num_cnot_configs, num_qubits))
        
    supernet_device_dir = supernet_dir + '/' + device_name
    
    if not os.path.exists(supernet_device_dir):
        os.mkdir(supernet_device_dir)
        
    for i in range(num_circs):
        curr_circ_desc = np.random.randint(0, search_space, num_layers)

        curr_params = np.concatenate([params[k, curr_circ_desc[k] // num_cnot_configs] for k in range(num_layers)]).flatten()

        circ_gates, gate_params, inputs_bounds, weights_bounds = convert_supernet_circ_into_gate_circ(curr_circ_desc, num_embed_layers, layer_rots, layer_cnots,
                                                                                                          num_qubits, False) 
        
        circ = create_gate_circ(dev, circ_gates, gate_params, inputs_bounds,
                                                                weights_bounds, [0, 1], 'exp')
        
        val_exp_list = []
        
        for j in range(len(x_test)):
            val_exp_list.append(circ(x_test[j], curr_params))
            
        val_exps = np.array(val_exp_list)
        val_losses = np.sum(np.power(val_exps - y_test, 2), 1)
        val_loss = np.mean(val_losses)
        acc = np.mean(np.sum(np.multiply(val_exps, y_test) > 0, 1) == 2)
            
        print(curr_circ_desc, acc, val_loss)

        accs.append(acc)
        losses.append(val_loss)
        circ_layers.append(curr_circ_desc)
        
    np.savetxt(supernet_device_dir + '/searched_circ_layers.txt', np.array(circ_layers))
    np.savetxt(supernet_device_dir + '/searched_circ_accs.txt', accs)
    np.savetxt(supernet_device_dir + '/searched_circ_losses.txt', losses)  
    np.savetxt(supernet_dir + '/searched_circ_accs.txt', ['{} {}'.format(circ_layers[i], accs[i]) for i in range(num_circs)], fmt="%s")

[ 16759 244661 244251] 0.3025 2.0480698585510253
[198537 165145  53605] 0.2175 2.124394817352295
[324512 195843 283072] 0.1925 2.263037977218628
[  8933  84217 122893] 0.18 2.112863540649414
[191823  10000 195366] 0.245 2.1265861129760744
[227634  75548 210459] 0.245 2.0062222385406496
[252493   5538 248847] 0.2475 2.08980619430542
[112833 162357  28365] 0.32 2.0238563442230224
[157945 328913 139326] 0.2725 2.1015180110931397
[198889 299294 205285] 0.1825 2.0491217041015624
[259028  95346 276633] 0.25 2.0395730781555175
[ 72629 247537 296947] 0.22 2.1193291568756103
[291331 139405  46101] 0.3225 2.002014646530151
[ 62133 158960 127000] 0.2425 2.083295421600342
[115907 253475 224613] 0.1675 2.255716600418091
[ 61156  85190 318671] 0.1875 2.172813587188721
[134279  31782   5907] 0.2325 2.134762935638428
[309474 300741  53255] 0.25 2.031287212371826
[ 41970  93863 309107] 0.335 1.9681832218170165
[  1606 124942  54228] 0.255 2.0482687377929687
[240936 141019 214987] 0.2425 2.1506838130950

In [ ]:
from datasets_nt import load_dataset
from create_gate_circs import create_gate_circ
from train_circ import mse_vec_loss, train_qnn
from create_noise_models import noisy_dev_from_backend

import pennylane as qml
import numpy as np
import os

dataset = 'fmnist_4'
main_dir = './supernet/fmnist_4/'

x_train, y_train, x_test, y_test = load_dataset(dataset, 'supernet', 1)

num_qubits = 4
num_cnot_configs = 4096
num_circs = 2500
num_embed_layers = 4
meas_qubits = [0, 1]
num_steps = 16000

dev = qml.device('lightning.qubit', wires=num_qubits)

param_nums = [12, 16, 20, 24]
search_nums = [100]
num_trials = [25]

device_name = 'ibmq_lima'
noisy_dev = noisy_dev_from_backend(device_name, num_qubits)

for p in param_nums:
    curr_params_dir =  main_dir + 'search-{}_params_mb'.format(p)

    layer_rots = open(curr_params_dir + '/rotations.txt').read().split('\n')[:-1]
    layer_rots = [''.join([j for j in i if j.isupper()]) for i in layer_rots]
    layer_rots = [[i[j * 2:j * 2 + 2].lower() for j in range(len(i) // 2)] for i in layer_rots]

    layer_cnots = open(curr_params_dir + '/cnots.txt').read().split('\n')[:-1]
    layer_cnots = [''.join([j for j in i[1:] if j not in ['[', ']', ',', ' ']]) for i in layer_cnots]
    layer_cnots = [[[int(i[2 * j]), int(i[2 * j + 1])] for j in range(len(i) // 2)] for i in layer_cnots]
        
    circ_accs = np.genfromtxt(curr_params_dir + '/{}/searched_circ_accs.txt'.format(device_name))
    circ_losses = np.genfromtxt(curr_params_dir + '/{}/searched_circ_losses.txt'.format(device_name))
    circ_layers = np.genfromtxt(curr_params_dir + '/{}/searched_circ_layers.txt'.format(device_name)).astype('int32').reshape((num_circs, p // num_qubits))

    for k in range(len(search_nums)):
        search_dir = curr_params_dir + '/{}/search_{}'.format(device_name, search_nums[k])

        if not os.path.exists(search_dir):
            os.mkdir(search_dir)

        for i in range(num_trials[k]):
            curr_dir = search_dir + '/trial_{}'.format(i + 1)

            if not os.path.exists(curr_dir):
                os.mkdir(curr_dir)

            chosen_circs = range(search_nums[k] * i, search_nums[k] * i + search_nums[k])
            best_circuit_ind = chosen_circs[np.argmax(circ_accs[chosen_circs])]
            best_subnet = circ_layers[best_circuit_ind]
            print(circ_accs[best_circuit_ind], circ_losses[best_circuit_ind], best_subnet)

            np.savetxt(curr_dir + '/sampled_circuits.txt', circ_layers[chosen_circs])
            np.savetxt(curr_dir + '/sampled_circuit_accs.txt', circ_accs[chosen_circs])

            circ_gates, gate_params, inputs_bounds, weights_bounds = convert_supernet_circ_into_gate_circ(best_subnet, num_embed_layers,
                                                                                                              layer_rots, layer_cnots, num_qubits, False)

            circ = create_gate_circ(dev, circ_gates, gate_params, inputs_bounds,
                                                                weights_bounds, meas_qubits, 'exp', 'adjoint') 
            
            noisy_circ = create_gate_circ(noisy_dev, circ_gates, gate_params, inputs_bounds,
                                                                weights_bounds, meas_qubits, 'exp', None)

            losses_list = []
            accs_list = []
            
            noisy_losses_list = []
            noisy_accs_list = []

            for j in range(5):
                curr_train_dir = curr_dir + '/run_{}'.format(j + 1)

                if os.path.exists(curr_train_dir):
                    pass
                else:
                    os.mkdir(curr_train_dir)


                info = train_qnn(circ, x_train, y_train, x_test, y_test, [weights_bounds[-1]], num_steps, 0.05, 1, mse_vec_loss, verbosity=17300, 
                                                                                                    loss_window=50, init_params=None, 
                                                                                                    acc_thres=1.1, shuffle=True, print_loss=50)
                
                np.savetxt(curr_train_dir + '/params_{}.txt'.format(j + 1), info[-1])
                np.savetxt(curr_train_dir + '/losses_{}.txt'.format(j + 1), info[0])

                val_exps = [circ(x_test[i], info[-1][-1]) for i in range(len(x_test))]
                val_loss = np.array([mse_vec_loss(y_test[k], val_exps[k]) for k in range(len(x_test))]).flatten()
                                
                noisy_val_exps = [noisy_circ(x_test[i], info[-1][-1]) for i in range(len(x_test))]
                noisy_val_loss = np.array([mse_vec_loss(y_test[k], noisy_val_exps[k]) for k in range(len(x_test))]).flatten()

                acc = np.mean(np.sum(np.multiply(val_exps, y_test) > 0, 1) == 2)
                noisy_acc = np.mean(np.sum(np.multiply(noisy_val_exps, y_test) > 0, 1) == 2)
#                 acc = np.mean(val_loss < 1)
#                 noisy_acc = np.mean(noisy_val_loss < 1)

                losses_list.append(val_loss)
                accs_list.append(acc)
                
                noisy_losses_list.append(noisy_val_loss)
                noisy_accs_list.append(noisy_acc)

            np.savetxt(curr_dir + '/accs.txt', accs_list)
            np.savetxt(curr_dir + '/val_losses.txt', losses_list)          
            
            np.savetxt(curr_dir + '/noisy_accs.txt', noisy_accs_list)
            np.savetxt(curr_dir + '/noisy_val_losses.txt', noisy_losses_list)  

            np.savetxt(curr_dir + '/gates.txt', circ_gates, fmt="%s")
            np.savetxt(curr_dir + '/gate_params.txt', gate_params, fmt="%s")
            np.savetxt(curr_dir + '/inputs_bounds.txt', inputs_bounds)
            np.savetxt(curr_dir + '/weights_bounds.txt', weights_bounds)
            np.savetxt(curr_dir + '/layers.txt', best_subnet)

ibmqfactory.load_account:WARNING:2022-10-09 05:37:37,334: Credentials are already in use. The existing account in the session will be replaced.


0.35 1.9747258949279785 [229057 117147 216266]
Step 1 | Sliding Loss Window : 1.5944306107894668
Step 51 | Sliding Loss Window : 1.4160922722436466
Step 101 | Sliding Loss Window : 1.473950122081884
Step 151 | Sliding Loss Window : 1.4777290925930697
Step 201 | Sliding Loss Window : 1.456162592183217
Step 251 | Sliding Loss Window : 1.3512596630090992
Step 301 | Sliding Loss Window : 1.3966874099866786
Step 351 | Sliding Loss Window : 1.4131629600821163
Step 401 | Sliding Loss Window : 1.4158659464859966
Step 451 | Sliding Loss Window : 1.3894152660994603
Step 501 | Sliding Loss Window : 1.3851500496732114
Step 551 | Sliding Loss Window : 1.4467829240657923
Step 601 | Sliding Loss Window : 1.383930014935733
Step 651 | Sliding Loss Window : 1.4372119872400158
Step 701 | Sliding Loss Window : 1.3880288186337715
Step 751 | Sliding Loss Window : 1.441848099169653
Step 801 | Sliding Loss Window : 1.3904458375327806
Step 851 | Sliding Loss Window : 1.4151843448413166
Step 901 | Sliding Loss 

## metric for correlation circuits

In [63]:
from create_gate_circs import generate_random_gate_circ, generate_true_random_gate_circ, create_gate_circ, create_batched_gate_circ, get_circ_params
from create_human_design_circs import generate_human_design_circ
from metrics import compute_reduced_similarity
from datasets import load_dataset

# ideal = np.concatenate((np.ones((16, 16)), np.zeros((16, 16)), np.zeros((16, 16)), np.zeros((16, 16))))
# ideal_2 = np.concatenate((np.zeros((16, 16)), np.ones((16, 16)), np.zeros((16, 16)), np.zeros((16, 16))))
# ideal = np.concatenate((ideal, ideal_2, ideal_2[::-1, :], ideal[::-1, :]), 1)

ideal = np.concatenate((np.ones((16, 16)), np.zeros((16, 16))))
ideal = np.concatenate((ideal, ideal[::-1, :]), 1)

curr_dir = './experiment_data/bank/trained_circuits'
num_qubits = 4
meas_qubits = [0]

x_train, y_train, x_test, y_test = load_dataset('bank', 'angle', 2)

# class_0_sel = np.random.choice(2000, 16, False)
# class_1_sel = np.random.choice(2000, 16, False) + 2000
# class_2_sel = np.random.choice(2000, 16, False) + 4000
# class_3_sel = np.random.choice(2000, 16, False) + 6000
# sel_inds = np.concatenate((class_0_sel, class_1_sel, class_2_sel, class_3_sel))

class_0_sel = np.random.choice(549, 16, False)
class_1_sel = np.random.choice(549, 16, False) + 549
sel_inds = np.concatenate((class_0_sel, class_1_sel))

sel_data = x_train[sel_inds]

num_params = 32
num_data = 32

d2_min_scores = []
d2_mean_scores = []
d2_var_scores = []
    
d2_t_min_scores = []
d2_t_mean_scores = []
d2_t_var_scores = []

mean_mat_scores = []
mean_t_mat_scores = []

# np.savetxt(curr_dir + '/fid_mats_sel_data.txt', sel_data)

for i in range(1000):
    circ_dir = curr_dir + '/circ_{}'.format(i + 1)
    
    circ_gates, gate_params, inputs_bounds, weights_bounds = get_circ_params(circ_dir)
    
    batched_circ = create_batched_gate_circ(qml.device('lightning.qubit', wires=num_qubits), circ_gates, gate_params, inputs_bounds,
                                        weights_bounds, meas_qubits, 'matrix') 
    
    params = 2 * np.pi * np.random.sample((num_params, weights_bounds[-1]))
    
    if not os.path.exists(circ_dir + '/fid_mats'):
        os.mkdir(circ_dir + '/fid_mats')
    
    np.savetxt(circ_dir + '/fid_mats/metric_params.txt', params) 
    
    circ_d2_scores = []
    circ_d2_t_scores = []
    circ_mean_mat = np.zeros((num_data, num_data))
    circ_t_mean_mat = np.zeros((num_data, num_data))
    
    for j in range(num_params):
        curr_params = np.concatenate([params[j] for k in range(num_data)]).reshape((num_data, weights_bounds[-1]))
        mat = compute_reduced_similarity(batched_circ, curr_params, sel_data)
        
        t_mat = mat > ((np.sum(mat) - num_data) / (num_data * (num_data - 1)))
        
        diff_mat = mat - ideal
        diff_2d = np.sum(np.multiply(diff_mat, diff_mat))
            
        diff_t_mat = t_mat - ideal
        diff_2d_t = np.sum(np.multiply(diff_t_mat, diff_t_mat))
            
        circ_d2_scores.append(diff_2d)
        circ_d2_t_scores.append(diff_2d_t)
            
        circ_mean_mat += mat / num_params
        circ_t_mean_mat += t_mat / num_params

    np.savetxt(circ_dir + '/fid_mats/d2_scores.txt', circ_d2_scores)
    np.savetxt(circ_dir + '/fid_mats/d2_t_scores.txt', circ_d2_t_scores)
        
    d2_min_scores.append(np.min(circ_d2_scores))
    d2_mean_scores.append(np.mean(circ_d2_scores))
    d2_var_scores.append(np.var(circ_d2_scores))
        
    d2_t_min_scores.append(np.min(circ_d2_t_scores))
    d2_t_mean_scores.append(np.mean(circ_d2_t_scores))
    d2_t_var_scores.append(np.var(circ_d2_t_scores))
        
    diff_mean_mat = ideal - circ_mean_mat
    diff_t_mean_mat = ideal - circ_t_mean_mat
        
    mean_mat_scores.append(np.sum(np.multiply(diff_mean_mat, diff_mean_mat)))
    mean_t_mat_scores.append(np.sum(np.multiply(diff_t_mean_mat, diff_t_mean_mat)))     
    
    print(i)
        
np.savetxt(curr_dir + '/d2_mean_scores_rd.txt', d2_mean_scores)
np.savetxt(curr_dir + '/d2_min_scores_rd.txt', d2_min_scores)
np.savetxt(curr_dir + '/d2_var_scores_rd.txt', d2_var_scores)
    
np.savetxt(curr_dir + '/d2_t_mean_scores_rd.txt', d2_t_mean_scores)
np.savetxt(curr_dir + '/d2_t_min_scores_rd.txt', d2_t_min_scores)
np.savetxt(curr_dir + '/d2_t_var_scores_rd.txt', d2_t_var_scores)
    
np.savetxt(curr_dir + '/d2_mean_mat_scores_rd.txt', mean_mat_scores)
np.savetxt(curr_dir + '/d2_mean_t_mat_scores_rd.txt', mean_t_mat_scores)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
27

## noise merrtric for correlation circuits

In [37]:
from importlib import reload

import metrics

reload(metrics)

<module 'metrics' from '/root/metrics.py'>

In [ ]:
from create_noise_models import get_real_backend_dev, noisy_dev_from_backend
from create_gate_circs import create_batched_gate_circ, get_circ_params
from datasets_nt import load_dataset
from metrics import compute_noise_metric

dataset = 'mnist_4'

x_train, y_train, _, __ = load_dataset(dataset, 'angle', 1)

curr_dir = './experiment_data/{}/trained_circuits'.format(dataset)

num_qubits = 4
num_trial_params = 128
meas_qubits = [0, 1, 2, 3]

num_cdcs = 128
num_shots = 1024

device_name = 'ibm_oslo'

dev = noisy_dev_from_backend(device_name, num_qubits)
noiseless_dev = qml.device('lightning.qubit', wires=num_qubits)

score_tvds = []
actual_tvds = []

for i in range(1000):
    circ_dir = curr_dir + '/circ_{}'.format(i + 1)
    
    circ_gates, gate_params, inputs_bounds, weights_bounds = get_circ_params(circ_dir)

    noisy_circ = create_batched_gate_circ(dev, circ_gates, gate_params, inputs_bounds,
                                                                weights_bounds, meas_qubits, 'probs') 

    noiseless_circ = create_batched_gate_circ(noiseless_dev, circ_gates, gate_params, inputs_bounds,
                                                                weights_bounds, meas_qubits, 'probs') 
    
    noise_metric_dir = circ_dir + '/noise_metric'
    
    if not os.path.exists(noise_metric_dir):
        os.mkdir(noise_metric_dir)
    
    device_noise_metric_dir = noise_metric_dir + '/{}'.format(device_name)

    if not os.path.exists(device_noise_metric_dir):
        os.mkdir(device_noise_metric_dir)
    
    params = np.random.sample((num_trial_params, weights_bounds[-1])) * 2 * np.pi
    batch_data = x_train[np.random.choice(len(x_train), num_trial_params, False)]
    
    noiseless_res_raw = np.array(noiseless_circ(batch_data, params, shots=num_shots))
    noisy_res_raw = np.array(noisy_circ(batch_data, params, shots=num_shots))

    actual_tvd = 1 - np.mean(np.sum(0.5 * np.abs(noiseless_res_raw - noisy_res_raw), 1))
    
    tvd = compute_noise_metric(circ_gates, gate_params, inputs_bounds, weights_bounds, num_qubits, noiseless_dev, dev, num_cdcs=num_cdcs, num_shots=num_shots)
    
    np.savetxt(device_noise_metric_dir + '/metric_tvd_score.txt', [1 - tvd])
    np.savetxt(device_noise_metric_dir + '/actual_tvd_score.txt', [actual_tvd])
    
    score_tvds.append(1 - tvd)
    actual_tvds.append(actual_tvd)
    
    print(1 - tvd, actual_tvd, i)

# np.savetxt(curr_dir + '/noise_scores.txt', score_tvds)
# np.savetxt(curr_dir + '/noisy_fids.txt', actual_tvds)

ibmqfactory.load_account:WARNING:2022-11-05 17:16:07,477: Credentials are already in use. The existing account in the session will be replaced.


0.48885345458984375 0.6273727416992188 0
0.448394775390625 0.5707321166992188 1
0.5422592163085938 0.62744140625 2
0.1306610107421875 0.45908355712890625 3
0.9370269775390625 0.9329986572265625 4
0.681671142578125 0.638092041015625 5
0.5296554565429688 0.6502456665039062 6
0.5391082763671875 0.62518310546875 7
0.397369384765625 0.6100997924804688 8
0.11624908447265625 0.1923065185546875 9
0.5491256713867188 0.5990982055664062 10
0.5663528442382812 0.6461105346679688 11
0.6049346923828125 0.638946533203125 12
0.41663360595703125 0.5781173706054688 13
0.25621795654296875 0.61279296875 14
0.46726226806640625 0.6193008422851562 15
0.6439208984375 0.6392974853515625 16
0.14154815673828125 0.5308609008789062 17
0.099273681640625 0.290435791015625 18
0.5119705200195312 0.6204986572265625 19
0.5901641845703125 0.6600570678710938 20
0.1539764404296875 0.2799530029296875 21
0.36664581298828125 0.60272216796875 22


In [ ]:
from create_noise_models import get_real_backend_dev, noisy_dev_from_backend
from create_gate_circs import create_batched_gate_circ, get_circ_params
from datasets_nt import load_dataset
from metrics import compute_noise_metric

dataset = 'fmnist_2'

x_train, y_train, _, __ = load_dataset(dataset, 'angle', 1)

curr_dir = './ours/{}'.format(dataset)

num_qubits = 4
num_trial_params = 128
meas_qubits = [0, 1, 2, 3]

param_nums = [16, 20, 24]

num_cdcs = 128
num_shots = 1024

device_name = 'ibmq_manila'

dev = noisy_dev_from_backend(device_name, num_qubits)
noiseless_dev = qml.device('lightning.qubit', wires=num_qubits)

score_tvds = []
actual_tvds = []

for p in param_nums:
    param_dir = curr_dir + '/{}_params'.format(p)
    
    for i in range(2500):
        circ_dir = param_dir + '/circ_{}'.format(i + 1)

        circ_gates, gate_params, inputs_bounds, weights_bounds = get_circ_params(circ_dir)

        noisy_circ = create_batched_gate_circ(dev, circ_gates, gate_params, inputs_bounds,
                                                                    weights_bounds, meas_qubits, 'probs') 

        noiseless_circ = create_batched_gate_circ(noiseless_dev, circ_gates, gate_params, inputs_bounds,
                                                                    weights_bounds, meas_qubits, 'probs') 

        noise_metric_dir = circ_dir + '/noise_metric'

        if not os.path.exists(noise_metric_dir):
            os.mkdir(noise_metric_dir)

        device_noise_metric_dir = noise_metric_dir + '/{}'.format(device_name)

        if not os.path.exists(device_noise_metric_dir):
            os.mkdir(device_noise_metric_dir)

        params = np.random.sample((num_trial_params, weights_bounds[-1])) * 2 * np.pi
        batch_data = x_train[np.random.choice(len(x_train), num_trial_params, False)]

        noiseless_res_raw = np.array(noiseless_circ(batch_data, params, shots=num_shots))
        noisy_res_raw = np.array(noisy_circ(batch_data, params, shots=num_shots))

        actual_tvd = 1 - np.mean(np.sum(0.5 * np.abs(noiseless_res_raw - noisy_res_raw), 1))

        tvd = compute_noise_metric(circ_gates, gate_params, inputs_bounds, weights_bounds, num_qubits, noiseless_dev, dev, num_cdcs=num_cdcs, num_shots=num_shots)

        np.savetxt(device_noise_metric_dir + '/metric_tvd_score.txt', [1 - tvd])
        np.savetxt(device_noise_metric_dir + '/actual_tvd_score.txt', [actual_tvd])

        score_tvds.append(1 - tvd)
        actual_tvds.append(actual_tvd)

        print(1 - tvd, actual_tvd, i)
        
    np.savetxt(param_dir + '/act_tvds.txt', actual_tvds)
    np.savetxt(param_dir + '/metric_tvds.txt', score_tvds)

ibmqfactory.load_account:WARNING:2022-11-08 09:51:18,431: Credentials are already in use. The existing account in the session will be replaced.


0.9087066650390625 0.9083328247070312 0
0.9159469604492188 0.9152755737304688 1
0.9278717041015625 0.9276199340820312 2
0.898345947265625 0.8939971923828125 3
0.8823471069335938 0.8664779663085938 4
0.9152679443359375 0.914764404296875 5
0.9094467163085938 0.9046478271484375 6
0.9123077392578125 0.9058303833007812 7
0.9082412719726562 0.9089813232421875 8
0.919769287109375 0.833770751953125 9
0.9387893676757812 0.938690185546875 10
0.91424560546875 0.910064697265625 11


## trin correlation circuits

In [ ]:
from datasets import TorchDataset
from create_gate_circs_np import get_circ_params, TQCirc, generate_true_random_gate_circ
from train_circ_np import train_tq_model, TQMseLoss

import pickle as pkl
import torch
import os
import numpy as np

dataset = 'vowel_4'
curr_dir = f'./experiment_data/{dataset}/trained_circuits/'

num_qubits = 4
num_embeds = 10

num_train_steps = 1000
num_test_data = 120

num_meas_qubits = 2

loss = TQMseLoss(num_meas_qubits, 4)

dev = qml.device('lightning.qubit', wires=4)
device = 'cpu'

train_data = TorchDataset(dataset, 'angle', 1, reshape_labels=False)
test_data = TorchDataset(dataset, 'angle', 1, False, reshape_labels=False)

train_data_loader = torch.utils.data.DataLoader(train_data, batch_size=32, sampler=torch.utils.data.RandomSampler(train_data))
test_data_loader = torch.utils.data.DataLoader(test_data, batch_size=32, sampler=torch.utils.data.SequentialSampler(test_data))

for i in range(800, 1000):    
    circ_dir = curr_dir + f'circ_{i + 1}'
    
    circ_gates, gate_params, inputs_bounds, weights_bounds = get_circ_params(circ_dir)

    losses_list = []
    accs_list = []
    
    for j in range(5):
        curr_train_dir = circ_dir + '/run_{}'.format(j + 1)
        
        if os.path.exists(curr_train_dir):
            pass
        else:
            os.mkdir(curr_train_dir)
    
        model = TQCirc(circ_gates, gate_params, inputs_bounds, weights_bounds, num_qubits, False).to(device)
        opt = torch.optim.SGD(model.parameters(), lr=0.05)
    
        curr_loss, curr_acc = train_tq_model(model, num_meas_qubits, opt, loss, train_data_loader, test_data_loader, num_test_data, num_train_steps, 100, 10)
        
        print(curr_loss, curr_acc)
        
        torch.save(model.state_dict(), curr_train_dir + '/model.pt')

        losses_list.append(curr_loss)
        accs_list.append(curr_acc)
        
    np.savetxt(circ_dir + '/val_losses.txt', losses_list)
    np.savetxt(circ_dir + '/accs.txt', accs_list)   

Step 1 | Loss: 3.1595458984375
Step 101 | Loss: 2.0766091346740723
Step 201 | Loss: 1.9927369356155396
Step 301 | Loss: 1.9895977973937988
Step 401 | Loss: 2.0106570720672607
Step 501 | Loss: 2.039660692214966
Step 601 | Loss: 2.0034120082855225
Step 701 | Loss: 1.9895917177200317
Step 801 | Loss: 2.0099053382873535
Step 901 | Loss: 1.9564239978790283
2.000083476128862 0.25
Step 1 | Loss: 4.224008083343506
Step 101 | Loss: 2.06237530708313
Step 201 | Loss: 1.9749430418014526
Step 301 | Loss: 1.9925868511199951
Step 401 | Loss: 2.02649188041687
Step 501 | Loss: 1.9579414129257202
Step 601 | Loss: 1.9649076461791992
Step 701 | Loss: 1.9938106536865234
Step 801 | Loss: 2.0008790493011475
Step 901 | Loss: 1.9954763650894165
1.9995712557631993 0.25
Step 1 | Loss: 2.0540924072265625
Step 101 | Loss: 1.985139012336731
Step 201 | Loss: 2.031766653060913
Step 301 | Loss: 2.0065431594848633
Step 401 | Loss: 1.9957431554794312
Step 501 | Loss: 1.9927666187286377
Step 601 | Loss: 2.007966756820678

In [82]:
from datasets import load_dataset
from create_gate_circs import create_gate_circ
from train_circ import train_qnn, mse_loss

dataset = 'moons_300'

x_train, y_train, x_test, y_test = load_dataset(dataset, 'angle', 2)

num_qubits = 2

for i in range(125, 126):
    curr_dir = './experiment_data/moons_300/trained_circuits/circ_{}'.format(i + 1)
    circ_gates, gate_params, inputs_bounds, weights_bounds = get_circ_params(curr_dir) 

    circ = create_gate_circ(qml.device('lightning.qubit', wires=num_qubits), circ_gates, gate_params, inputs_bounds,
                                                    weights_bounds, [0], 'exp')    

    losses_list = []
    accs_list = []
    
    for j in range(1):
        curr_train_dir = curr_dir + '/run_{}'.format(j + 1)

        if os.path.exists(curr_train_dir):
            pass
        else:
            os.mkdir(curr_train_dir)
    
        
        info = train_qnn(circ, x_train, y_train, x_test, y_test, [weights_bounds[-1]], 12000, 0.05, 1, mse_loss, verbosity=730300, 
                                                                                        loss_window=5, init_params=None, 
                                                                                        acc_thres=1.1, shuffle=True, print_loss=250)
        
        val_exps = [circ(x_test[i], info[-1][-1]) for i in range(len(x_test))]
        val_loss = np.array([mse_loss(y_test[k], val_exps[k]) for k in range(len(x_test))]).flatten()

        acc = np.mean(val_loss < 1)
        
#         np.savetxt(curr_train_dir + '/params_{}.txt'.format(j + 1), info[-1])
#         np.savetxt(curr_train_dir + '/losses_{}.txt'.format(j + 1), info[0])
        
        losses_list.append(val_loss)
        accs_list.append(acc)
        
#     np.savetxt(curr_dir + '/val_losses.txt', losses_list)
#     np.savetxt(curr_dir + '/accs.txt', accs_list)

Step 1 | Sliding Loss Window : 3.7047800310027426
Step 251 | Sliding Loss Window : 1.0217753300500967
Step 501 | Sliding Loss Window : 0.7854476574748885
Step 751 | Sliding Loss Window : 0.7636520767276398
Step 1001 | Sliding Loss Window : 0.908174914433529
Step 1251 | Sliding Loss Window : 0.28577256609749
Step 1501 | Sliding Loss Window : 0.925198879708115
Step 1751 | Sliding Loss Window : 0.858156845648109
Step 2001 | Sliding Loss Window : 0.19096731550977575


KeyboardInterrupt: 

In [14]:
from importlib import reload

import datasets
import create_gate_circs
import train_circ

reload(datasets)
reload(create_gate_circs)
reload(train_circ)

<module 'train_circ' from '/root/train_circ.py'>

In [ ]:
from datasets import TorchDataset
from create_gate_circs import get_circ_params, TQCirc, generate_random_gate_circ
from train_circ import train_tq_model

import pickle as pkl
import torch
import os
import numpy as np

num_qubits = 10

device = torch.device('cpu')

dataset = 'mnist_10'

train_data = TorchDataset(dataset, 'angle', 1, True)
test_data = TorchDataset(dataset, 'angle', 1, False)

train_data_loader = torch.utils.data.DataLoader(train_data, batch_size=1, sampler=torch.utils.data.RandomSampler(train_data))
test_data_loader = torch.utils.data.DataLoader(train_data, batch_size=1, sampler=torch.utils.data.RandomSampler(train_data))

val_test_data_loader = torch.utils.data.DataLoader(test_data, batch_size=100, sampler=torch.utils.data.SequentialSampler(test_data))

loss = torch.nn.functional.nll_loss
val_loss = torch.nn.NLLLoss(reduction='none')

for i in range(18, 25):
    curr_dir = './experiment_data/{}/trained_circuits/circ_{}'.format(dataset, i + 1)

    circ_gates, gate_params, inputs_bounds, weights_bounds = get_circ_params(curr_dir) 

    model = TQCirc(circ_gates, gate_params, inputs_bounds, weights_bounds, num_qubits, True).to(device)
    opt = torch.optim.SGD(model.parameters(), lr=0.05)
    
    losses_list = []
    accs_list = []
    
    for j in range(1):
        curr_train_dir = curr_dir + '/run_{}'.format(j + 1)

        if os.path.exists(curr_train_dir):
            pass
        else:
            os.mkdir(curr_train_dir)
    
        accs_history = train_tq_model(model, opt, loss, train_data_loader, test_data_loader, 120000, 1000, 1000)
        
#         curr_val_losses = []
#         curr_acc = 0
        
#         for k in range(100):
#             val_x, val_y = next(iter(val_test_data_loader))

#             val_preds = model(val_x)
#             curr_val_losses.append(val_loss(val_preds, val_y.to(torch.long)).detach().numpy().flatten())
        
#             val_class = torch.argmax(val_preds.detach(), 1).detach().numpy().flatten()

#             curr_acc += np.mean(val_class == val_y.detach().numpy().flatten())
        
#         np.save(curr_train_dir + '/accs_history_{}.npy'.format(j + 1), accs_history)
        
#         losses_list.append(curr_val_losses)
#         accs_list.append(curr_acc / 100)
        
#         print(curr_acc)
        
    torch.save(model.state_dict(), curr_dir + '/model.pt')
#     np.save(curr_dir + '/val_losses.npy', losses_list)
#     np.savetxt(curr_dir + '/accs.txt', accs_list)

Step 1 | Accuracy: 0.0
Step 1001 | Accuracy: 0.0
Step 2001 | Accuracy: 1.0
Step 3001 | Accuracy: 0.0
Step 4001 | Accuracy: 1.0
Step 5001 | Accuracy: 0.0
Step 6001 | Accuracy: 1.0
Step 7001 | Accuracy: 1.0
Step 8001 | Accuracy: 0.0
Step 9001 | Accuracy: 1.0
Step 10001 | Accuracy: 1.0
Step 11001 | Accuracy: 0.0
Step 12001 | Accuracy: 0.0
Step 13001 | Accuracy: 1.0
Step 14001 | Accuracy: 0.0
Step 15001 | Accuracy: 0.0
Step 16001 | Accuracy: 1.0
Step 17001 | Accuracy: 0.0
Step 18001 | Accuracy: 0.0
Step 19001 | Accuracy: 0.0
Step 20001 | Accuracy: 0.0
Step 21001 | Accuracy: 0.0
Step 22001 | Accuracy: 0.0
Step 23001 | Accuracy: 1.0
Step 24001 | Accuracy: 0.0
Step 25001 | Accuracy: 0.0
Step 26001 | Accuracy: 1.0
Step 27001 | Accuracy: 0.0
Step 28001 | Accuracy: 0.0
Step 29001 | Accuracy: 0.0
Step 30001 | Accuracy: 0.0
Step 31001 | Accuracy: 0.0
Step 32001 | Accuracy: 0.0
Step 33001 | Accuracy: 1.0
Step 34001 | Accuracy: 0.0
Step 35001 | Accuracy: 0.0
Step 36001 | Accuracy: 1.0
Step 37001 | A